export const HELLO_WORLD = 'HELLO_WORLD';
// GLOBAL AUTH ACTIONS ---
export const AUTH_START = 'AUTH_START';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_CLEAR = 'AUTH_CLEAR';

// CREATOR AUTH ACTIONS ---
export const CREATOR_AUTH_START = 'CREATOR_AUTH_START';
export const CREATOR_AUTH_FAILURE = 'CREATOR_AUTH_FAILURE';
export const CREATOR_AUTH_SUCCESS = 'CREATOR_AUTH_SUCCESS';
export const CREATOR_AUTH_LOGOUT = 'CREATOR_AUTH_LOGOUT';

// CREATOR PROFILE ACTIONS
export const CREATOR_GET_PROFILE_INFO = 'CREATOR_GET_PROFILE_INFO';
export const CREATOR_UPDATE_PROFILE_INFO = 'CREATOR_UPDATE_PROFILE_INFO';

// BRAND AUTH ACTIONS ---
export const BRAND_AUTH_START = 'BRAND_AUTH_START';
export const BRAND_AUTH_FAILURE = 'BRAND_AUTH_FAILURE';
export const BRAND_AUTH_SUCCESS = 'BRAND_AUTH_SUCCESS';
export const BRAND_AUTH_LOGOUT = 'BRAND_AUTH_LOGOUT';

// BRAND GET CREATOR ACTIONS
export const BRAND_GET_CREATORS = 'BRAND_GET_CREATORS';
export const BRAND_UPDATE_FILTERS = 'BRAND_UPDATE_FILTERS';
export const BRAND_LOAD_START = 'BRAND_LOAD_START';
export const BRAND_LOAD_FAIL = 'BRAND_LOAD_FAIL';
export const BRAND_UPDATE_PAGE = 'BRAND_UPDATE_PAGE';

// BRAND CREATE NEW CAMPAIGN ACTIONS
export const BRAND_NEW_CAMPAIGN_UPDATE = 'BRAND_NEW_CAMPAIGN_UPDATE';
export const BRAND_NEW_CAMPAIGN = 'BRAND_NEW_CAMPAIGN';
export const BRAND_GET_CAMPAIGNS = 'BRAND_GET_CAMPAIGNS';
